### ISSUE TITLE
renameFQGZ.bash behaving unpredictably

### ISSUE THREAD

**Issue by nerdbrained** [philippinespire/pire_fq_gz_processing#2]
Not sure why but the rename script does not consistently give the correct names - here are three outputs from running an identical command (`bash /home/e1garcia/shotgun_PIRE/pire_fq_gz_processing/renameFQGZ.bash Sob_ProbeDevelopmentLibraries_SequenceNameDecode.tsv` from `/home/e1garcia/shotgun_PIRE/pire_ssl_data_processing/sphyraena_obtusata`):

output 1 (correct):
preview of orig and new R1 file names...
SoC0301809F_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9F-ssl_L2_1.fq.gz
SoC0301809G_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9G-ssl_L2_1.fq.gz
SoC0301809H_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9H-ssl_L2_1.fq.gz

output 2 (incorrect):
preview of orig and new R1 file names...
SoC0301809F_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9F-ssl_L2_1.fq.gz
SoC0301809G_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz SoC0301809G_L2_1.fq.gz
SoC0301809H_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9H-ssl_L2_1.fq.gz

output 3 (incorrect):
preview of orig and new R1 file names...
SoC0301809F_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9F-ssl_L2_1.fq.gz
SoC0301809G_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9G-ssl_L2_1.fq.gz
SoC0301809H_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz SoC0301809H_L2_1.fq.gz

It seems to get the correct naming scheme ~50% of the time?

We are using an updated naming scheme now so that might be causing some issues, but not sure why the outputs aren't reproducibly right or wrong...

**Comment by cbird808** [comment]
These files have a fundamental naming problem with all the underscores...   that could be part of it.  I'm going to make dummy files with these names in this place to test

From: nerdbrained ***@***.***>
Sent: Tuesday, September 20, 2022 9:38 AM
To: philippinespire/pire_fq_gz_processing ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [philippinespire/pire_fq_gz_processing] renameFQGZ.bash behaving unpredictably (Issue #2)


Not sure why but the rename script does not consistently give the correct names - here are three outputs from running an identical command (bash /home/e1garcia/shotgun_PIRE/pire_fq_gz_processing/renameFQGZ.bash Sob_ProbeDevelopmentLibraries_SequenceNameDecode.tsv from /home/e1garcia/shotgun_PIRE/pire_ssl_data_processing/sphyraena_obtusata):

output 1 (correct):
preview of orig and new R1 file names...
SoC0301809F_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9F-ssl_L2_1.fq.gz
SoC0301809G_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9G-ssl_L2_1.fq.gz
SoC0301809H_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9H-ssl_L2_1.fq.gz

output 2 (incorrect):
preview of orig and new R1 file names...
SoC0301809F_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9F-ssl_L2_1.fq.gz
SoC0301809G_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz SoC0301809G_L2_1.fq.gz
SoC0301809H_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9H-ssl_L2_1.fq.gz

output 3 (incorrect):
preview of orig and new R1 file names...
SoC0301809F_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9F-ssl_L2_1.fq.gz
SoC0301809G_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz Sob-CKal_018_Ex2-9G-ssl_L2_1.fq.gz
SoC0301809H_CKDL220019624-1A_H7TTHDSX5_L2_1.fq.gz SoC0301809H_L2_1.fq.gz

It seems to get the correct naming scheme ~50% of the time?

We are using an updated naming scheme now so that might be causing some issues, but not sure why the outputs aren't reproducibly right or wrong...

-

**Comment by nerdbrained** [comment]
Tried the current renameFQGZ.bash script on Ssp cssl data (in /home/e1garcia/shotgun_PIRE/pire_cssl_data_processing/siganus_spinus/raw_fq_capture). Still does not seem to be working as intended - it seems like it does consistently strip out the library-specific strings of #s/characters that are appended to all of the filenames (CKDL220019624-1A_H7TTHDSX5), but it only sometimes correctly replaces the individual-specific identifiers (8 characters after SsA/SsC) with the correct location/individual ID.

Rename files here:
https://github.com/philippinespire/pire_cssl_data_processing/blob/main/siganus_spinus/raw_fq_capture/newFileNames.txt
https://github.com/philippinespire/pire_cssl_data_processing/blob/main/siganus_spinus/raw_fq_capture/origFileNames.txt 

Note also that even the new filenames that look good have multiple underscores so may not be ddocent compliant.

**Comment by ericgarciaresearch** [comment]
Issue has been solved
